-- AlterTable
ALTER TABLE `SleepLog` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `SleepCheck` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sleepLogId` INTEGER NOT NULL,
    `checkedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SleepCheck` ADD CONSTRAINT `SleepCheck_sleepLogId_fkey` FOREIGN KEY (`sleepLogId`) REFERENCES `SleepLog`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
